const initialState = {
  // Use "initialState" with a capital "S"
  sellinforecast: false,
  selloutforecast: false,
  oosrisk: false,
  irregularpo: false,
  reallocation: false,
  filterstatus: false,
  userDetails: {
    Name: "Moka Keerthi",
    Email: "keerthi.moka@artefact.com",
    Customer: ["Asda", "Amazon"],
    Location: ["United Kingdom", "Australia"],
    Brand: ["Airwick", "Durex"],
    "Business Unit": ["Nutrition", "Hygiene", "Health"],
    Role: "admin",
  },
  overviewhighriskdata: [
    {
      "Active Promo": "Yes",
      Brand: "Harpic",
      "Comment RootCause":
        "factory delays and SOF, stock being loaded 27.06, ETA 12.07;  C0 - Factory & Supply Planning related issue;  ;  0",
      Description: "HARPC,GB,6X8 TAB,LAV CLNR",
      "Exp NR CW": 2801.74,
      "Exp NR CW+1": 5912.99,
      "Exp NR CW+2": 9814.04,
      "Exp NR CW+3": 6362.18,
      "OLA PCT CW": 0.93,
      "OLA PCT CW+1": 0.74,
      "OLA PCT CW+2": 0.88,
      "OLA PCT CW+3": 0.95,
      PPG: 9920845,
      "RAG CW": "A",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3028027,
      "Reason Code": "E0",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "No",
      Brand: "Airwick",
      "Comment RootCause": ";  ;  ;  0",
      Description: "AWICK,GB,PANDORA VANILLA",
      "Exp NR CW": 8727.12,
      "Exp NR CW+1": 6580.38,
      "Exp NR CW+2": 2547.08,
      "Exp NR CW+3": 5499.84,
      "OLA PCT CW": 0.88,
      "OLA PCT CW+1": 0.71,
      "OLA PCT CW+2": 0.71,
      "OLA PCT CW+3": 0.72,
      PPG: 8952547,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3126431,
      "Reason Code": "E2",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "No",
      Brand: "Finish",
      "Comment RootCause": ";  ;  ;  0",
      Description: "FINSH,GB,DWC REGLR 8X250ML",
      "Exp NR CW": 1604.63,
      "Exp NR CW+1": 481.34,
      "Exp NR CW+2": 1491.35,
      "Exp NR CW+3": 9357.35,
      "OLA PCT CW": 0.92,
      "OLA PCT CW+1": 0.92,
      "OLA PCT CW+2": 0.69,
      "OLA PCT CW+3": 0.76,
      PPG: 8289222,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3249097,
      "Reason Code": "E0",
      "Reckitt WOC": 2.8,
    },
    {
      "Active Promo": "No",
      Brand: "Airwick",
      "Comment RootCause":
        ";  ;  ;  approx 3300 cs was sped up for end of wk 28 (PMs not confirmed yet)",
      Description: "AWICK,GB,EUCFREES 8X237ML",
      "Exp NR CW": 9218.49,
      "Exp NR CW+1": 3688.21,
      "Exp NR CW+2": 901.02,
      "Exp NR CW+3": 8948.62,
      "OLA PCT CW": 0.75,
      "OLA PCT CW+1": 0.74,
      "OLA PCT CW+2": 0.8,
      "OLA PCT CW+3": 0.75,
      PPG: 1710831,
      "RAG CW": "A",
      "RAG CW+1": "G",
      "RAG CW+2": "A",
      "RAG CW+3": "G",
      "RB SKU": 3168444,
      "Reason Code": "E3",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "Yes",
      Brand: "Airwick",
      "Comment RootCause": ";  B0 - S&OP/Demand Planning;  ;  0",
      Description: "AWICK,GB,DOLPHIN MEDSUN *6",
      "Exp NR CW": 626.48,
      "Exp NR CW+1": 1264.46,
      "Exp NR CW+2": 7085.81,
      "Exp NR CW+3": 4680.48,
      "OLA PCT CW": 0.72,
      "OLA PCT CW+1": 0.95,
      "OLA PCT CW+2": 0.73,
      "OLA PCT CW+3": 0.93,
      PPG: 7002824,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3013422,
      "Reason Code": "E1",
      "Reckitt WOC": 2.0,
    },
    {
      "Active Promo": "Yes",
      Brand: "Finish",
      "Comment RootCause":
        "Obsolete ;  L0 - Obsolete / Discontinued items;  ;  0",
      Description: "FINSH,GB,PWR ESS LEM 16X15TABS",
      "Exp NR CW": 4822.97,
      "Exp NR CW+1": 2860.23,
      "Exp NR CW+2": 4401.06,
      "Exp NR CW+3": 3838.75,
      "OLA PCT CW": 0.87,
      "OLA PCT CW+1": 0.66,
      "OLA PCT CW+2": 0.76,
      "OLA PCT CW+3": 0.72,
      PPG: 1670250,
      "RAG CW": "G",
      "RAG CW+1": "R",
      "RAG CW+2": "R",
      "RAG CW+3": "G",
      "RB SKU": 3205612,
      "Reason Code": "E0",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "No",
      Brand: "Finish",
      "Comment RootCause":
        "Obsolete;  L0 - Obsolete / Discontinued items;  ;  0",
      Description: "FINSH,GB,POWER AIO REG 4X80TAB",
      "Exp NR CW": 2306.49,
      "Exp NR CW+1": 9833.61,
      "Exp NR CW+2": 2657.59,
      "Exp NR CW+3": 1286.49,
      "OLA PCT CW": 0.88,
      "OLA PCT CW+1": 0.87,
      "OLA PCT CW+2": 0.75,
      "OLA PCT CW+3": 0.74,
      PPG: 5275881,
      "RAG CW": "R",
      "RAG CW+1": "R",
      "RAG CW+2": "R",
      "RAG CW+3": "G",
      "RB SKU": 3204693,
      "Reason Code": "E1",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "No",
      Brand: "Calgon",
      "Comment RootCause": ";  ;  ;  0",
      Description: "CALGN,GB,HYGIENE GEL 1.2L",
      "Exp NR CW": 7421.23,
      "Exp NR CW+1": 3439.46,
      "Exp NR CW+2": 2223.13,
      "Exp NR CW+3": 6646.96,
      "OLA PCT CW": 0.79,
      "OLA PCT CW+1": 0.75,
      "OLA PCT CW+2": 0.95,
      "OLA PCT CW+3": 0.71,
      PPG: 8583822,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3264603,
      "Reason Code": "E3",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "No",
      Brand: "Airwick",
      "Comment RootCause": ";  ;  ;  0",
      Description: "AWICK,GB,CRISP LNN RF3X2X250ML",
      "Exp NR CW": 835.82,
      "Exp NR CW+1": 2654.74,
      "Exp NR CW+2": 131.49,
      "Exp NR CW+3": 7577.6,
      "OLA PCT CW": 0.95,
      "OLA PCT CW+1": 0.93,
      "OLA PCT CW+2": 0.71,
      "OLA PCT CW+3": 0.92,
      PPG: 1762699,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3251952,
      "Reason Code": "E1",
      "Reckitt WOC": 2.0,
    },
    {
      "Active Promo": "No",
      Brand: "Airwick",
      "Comment RootCause": ";  ;  ;  0",
      Description: "AWICK,GB,FM PUR SPRG 3X2X250ML",
      "Exp NR CW": 1940.62,
      "Exp NR CW+1": 1835.99,
      "Exp NR CW+2": 5005.81,
      "Exp NR CW+3": 2681.03,
      "OLA PCT CW": 0.69,
      "OLA PCT CW+1": 0.89,
      "OLA PCT CW+2": 0.7,
      "OLA PCT CW+3": 0.93,
      PPG: 8190542,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3240631,
      "Reason Code": "E0",
      "Reckitt WOC": 2.0,
    },
    {
      "Active Promo": "Yes",
      Brand: "Vanish",
      "Comment RootCause": "At SS;  ;  ;  0",
      Description: "VANSH,GB,GOLD WHT 6X1.5KG",
      "Exp NR CW": 9501.4,
      "Exp NR CW+1": 1868.63,
      "Exp NR CW+2": 7381.05,
      "Exp NR CW+3": 4382.62,
      "OLA PCT CW": 0.91,
      "OLA PCT CW+1": 0.91,
      "OLA PCT CW+2": 0.8,
      "OLA PCT CW+3": 0.86,
      PPG: 5379724,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3258416,
      "Reason Code": "E3",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "No",
      Brand: "Harpic",
      "Comment RootCause": "allocating stock from 1200;  ;  ;  0",
      Description: "HARPC,GB,BL,EUCALYPTS 12X750ML",
      "Exp NR CW": 2502.2,
      "Exp NR CW+1": 5507.44,
      "Exp NR CW+2": 1170.8,
      "Exp NR CW+3": 6827.93,
      "OLA PCT CW": 0.85,
      "OLA PCT CW+1": 0.81,
      "OLA PCT CW+2": 0.82,
      "OLA PCT CW+3": 0.68,
      PPG: 8736023,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3038099,
      "Reason Code": "E1",
      "Reckitt WOC": 2.0,
    },
    {
      "Active Promo": "No",
      Brand: "Airwick",
      "Comment RootCause": ";  ;  ;  0",
      Description: "AWICK,GB,PINEAP AMB CDL 1X500G",
      "Exp NR CW": 5824.88,
      "Exp NR CW+1": 7014.73,
      "Exp NR CW+2": 5980.74,
      "Exp NR CW+3": 9999.09,
      "OLA PCT CW": 0.95,
      "OLA PCT CW+1": 0.91,
      "OLA PCT CW+2": 0.73,
      "OLA PCT CW+3": 0.82,
      PPG: 3998963,
      "RAG CW": "A",
      "RAG CW+1": "A",
      "RAG CW+2": "A",
      "RAG CW+3": "A",
      "RB SKU": 3188839,
      "Reason Code": "E1",
      "Reckitt WOC": 6.0,
    },
    {
      "Active Promo": "No",
      Brand: "Airwick",
      "Comment RootCause":
        "SOF driven by B&M, ProdOrd: 7509 on 01/07& that will bring us back to SS;  B0 - S&OP/Demand Planning;  ;  0",
      Description: "AWICK,GB,FM RF WRP 3X2X250ML",
      "Exp NR CW": 8063.25,
      "Exp NR CW+1": 8976.12,
      "Exp NR CW+2": 1686.29,
      "Exp NR CW+3": 4775.5,
      "OLA PCT CW": 0.76,
      "OLA PCT CW+1": 0.77,
      "OLA PCT CW+2": 0.88,
      "OLA PCT CW+3": 0.68,
      PPG: 3858094,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3247127,
      "Reason Code": "E2",
      "Reckitt WOC": 2.0,
    },
    {
      "Active Promo": "No",
      Brand: "Finish",
      "Comment RootCause": ";  ;  ;  0",
      Description: "FINSH,GB,POWER AIO REG6X20TAB",
      "Exp NR CW": 8136.01,
      "Exp NR CW+1": 7287.58,
      "Exp NR CW+2": 7425.15,
      "Exp NR CW+3": 4030.55,
      "OLA PCT CW": 0.91,
      "OLA PCT CW+1": 0.77,
      "OLA PCT CW+2": 0.94,
      "OLA PCT CW+3": 0.83,
      PPG: 6110344,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3205208,
      "Reason Code": "E1",
      "Reckitt WOC": 2.4,
    },
    {
      "Active Promo": "No",
      Brand: "Calgon",
      "Comment RootCause":
        "Not at SS - OOS risk WC 17.07;  B0 - S&OP/Demand Planning;  0;  0",
      Description: "CALGN,GB,4 IN ONE 5X45 TABS",
      "Exp NR CW": 8034.88,
      "Exp NR CW+1": 5630.77,
      "Exp NR CW+2": 3510.68,
      "Exp NR CW+3": 7724.66,
      "OLA PCT CW": 0.93,
      "OLA PCT CW+1": 0.77,
      "OLA PCT CW+2": 0.66,
      "OLA PCT CW+3": 0.68,
      PPG: 2069202,
      "RAG CW": "R",
      "RAG CW+1": "R",
      "RAG CW+2": "A",
      "RAG CW+3": "G",
      "RB SKU": 3248070,
      "Reason Code": "E1",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "No",
      Brand: "Calgon",
      "Comment RootCause":
        "Obsolete - Rekey to 3246420;  L0 - Obsolete / Discontinued items;  ;  0",
      Description: "CALGN,GB,GEL,6X750ML",
      "Exp NR CW": 2322.48,
      "Exp NR CW+1": 9300.38,
      "Exp NR CW+2": 1125.6,
      "Exp NR CW+3": 1403.59,
      "OLA PCT CW": 0.71,
      "OLA PCT CW+1": 0.79,
      "OLA PCT CW+2": 0.69,
      "OLA PCT CW+3": 0.69,
      PPG: 8085920,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 8083252,
      "Reason Code": "E1",
      "Reckitt WOC": 2.4,
    },
    {
      "Active Promo": "Yes",
      Brand: "Finish",
      "Comment RootCause": "NPD;  ;  ;  0",
      Description: "FINSH,GB,PWR ESS REG 7X50TABS",
      "Exp NR CW": 3755.36,
      "Exp NR CW+1": 9636.49,
      "Exp NR CW+2": 450.96,
      "Exp NR CW+3": 3002.49,
      "OLA PCT CW": 0.78,
      "OLA PCT CW+1": 0.67,
      "OLA PCT CW+2": 0.8,
      "OLA PCT CW+3": 0.9,
      PPG: 2637730,
      "RAG CW": "R",
      "RAG CW+1": "R",
      "RAG CW+2": "R",
      "RAG CW+3": "R",
      "RB SKU": 3261397,
      "Reason Code": "E1",
      "Reckitt WOC": 3.0,
    },
    {
      "Active Promo": "Yes",
      Brand: "Finish",
      "Comment RootCause": ";  ;  ;  0",
      Description: "FINSH,GB,QTM ULT LEM 4X100TABS",
      "Exp NR CW": 2535.44,
      "Exp NR CW+1": 6671.96,
      "Exp NR CW+2": 9698.94,
      "Exp NR CW+3": 1766.75,
      "OLA PCT CW": 0.87,
      "OLA PCT CW+1": 0.84,
      "OLA PCT CW+2": 0.91,
      "OLA PCT CW+3": 0.88,
      PPG: 9931973,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3204725,
      "Reason Code": "E1",
      "Reckitt WOC": 2.4,
    },
    {
      "Active Promo": "No",
      Brand: "Airwick",
      "Comment RootCause": ";  ;  ;  0",
      Description: "AWICK,GB,LE KIT WRP 4X19ML",
      "Exp NR CW": 1761.68,
      "Exp NR CW+1": 4903.32,
      "Exp NR CW+2": 1282.69,
      "Exp NR CW+3": 8177.28,
      "OLA PCT CW": 0.81,
      "OLA PCT CW+1": 0.78,
      "OLA PCT CW+2": 0.69,
      "OLA PCT CW+3": 0.69,
      PPG: 9465786,
      "RAG CW": "G",
      "RAG CW+1": "G",
      "RAG CW+2": "G",
      "RAG CW+3": "G",
      "RB SKU": 3247350,
      "Reason Code": "E3",
      "Reckitt WOC": 3.0,
    },
  ],
  stockreallocation: [
    {
      "Business Unit": "Hygiene",
      Channel: "PurePlay",
      Customer: "Amazon",
      Location: "United Kingdom",
      allocationconsumed: 272,
      cmuscore: 5.18,
      currentallocation: 300,
      "custsoh-current": 300,
      "custsoh-target": 600,
      "custwoc-current": 3,
      "custwoc-target": 6,
      expectedservicelevel: 0.88,
      openorders: 272,
      remainingallocation: 28,
      "sif-atf": 300,
      "sif-reckitt": 700,
      stocksafetoreallocate: 254,
      suggestedallocation: 224,
    },
    {
      "Business Unit": "Health",
      Channel: "PurePlay",
      Customer: "Amazon",
      Location: "India",
      allocationconsumed: 519,
      cmuscore: 5.29,
      currentallocation: 700,
      "custsoh-current": 1000,
      "custsoh-target": 500,
      "custwoc-current": 6,
      "custwoc-target": 7,
      expectedservicelevel: 0.93,
      openorders: 519,
      remainingallocation: 181,
      "sif-atf": 200,
      "sif-reckitt": 300,
      stocksafetoreallocate: 200,
      suggestedallocation: 69,
    },
    {
      "Business Unit": "Health",
      Channel: "Groceries",
      Customer: "Asda",
      Location: "India",
      allocationconsumed: 150,
      cmuscore: 0.42,
      currentallocation: 200,
      "custsoh-current": 500,
      "custsoh-target": 600,
      "custwoc-current": 5,
      "custwoc-target": 10,
      expectedservicelevel: 0.88,
      openorders: 150,
      remainingallocation: 50,
      "sif-atf": 500,
      "sif-reckitt": 400,
      stocksafetoreallocate: 142,
      suggestedallocation: 110,
    },
    {
      "Business Unit": "Nutrition",
      Channel: "Pharmacy",
      Customer: "Amazon",
      Location: "United Kingdom",
      allocationconsumed: 300,
      cmuscore: 2.56,
      currentallocation: 1000,
      "custsoh-current": 300,
      "custsoh-target": 1000,
      "custwoc-current": 4,
      "custwoc-target": 5,
      expectedservicelevel: 0.95,
      openorders: 300,
      remainingallocation: 700,
      "sif-atf": 700,
      "sif-reckitt": 600,
      stocksafetoreallocate: 163,
      suggestedallocation: 12,
    },
    {
      "Business Unit": "Health",
      Channel: "Pharmacy",
      Customer: "Amazon",
      Location: "United Kingdom",
      allocationconsumed: 153,
      cmuscore: 2.72,
      currentallocation: 400,
      "custsoh-current": 500,
      "custsoh-target": 500,
      "custwoc-current": 4,
      "custwoc-target": 7,
      expectedservicelevel: 0.95,
      openorders: 153,
      remainingallocation: 247,
      "sif-atf": 700,
      "sif-reckitt": 300,
      stocksafetoreallocate: 143,
      suggestedallocation: 89,
    },
    {
      "Business Unit": "Health",
      Channel: "Pharmacy",
      Customer: "Amazon",
      Location: "Germany",
      allocationconsumed: 200,
      cmuscore: 9.72,
      currentallocation: 1000,
      "custsoh-current": 200,
      "custsoh-target": 800,
      "custwoc-current": 9,
      "custwoc-target": 11,
      expectedservicelevel: 0.91,
      openorders: 200,
      remainingallocation: 800,
      "sif-atf": 200,
      "sif-reckitt": 700,
      stocksafetoreallocate: 88,
      suggestedallocation: 80,
    },
    {
      "Business Unit": "Health",
      Channel: "Groceries",
      Customer: "Asda",
      Location: "Germany",
      allocationconsumed: 260,
      cmuscore: 8.76,
      currentallocation: 500,
      "custsoh-current": 600,
      "custsoh-target": 400,
      "custwoc-current": 4,
      "custwoc-target": 4,
      expectedservicelevel: 0.87,
      openorders: 260,
      remainingallocation: 240,
      "sif-atf": 600,
      "sif-reckitt": 600,
      stocksafetoreallocate: 67,
      suggestedallocation: 16,
    },
    {
      "Business Unit": "Hygiene",
      Channel: "Groceries",
      Customer: "Asda",
      Location: "India",
      allocationconsumed: 33,
      cmuscore: 0.34,
      currentallocation: 200,
      "custsoh-current": 800,
      "custsoh-target": 500,
      "custwoc-current": 3,
      "custwoc-target": 6,
      expectedservicelevel: 0.92,
      openorders: 33,
      remainingallocation: 167,
      "sif-atf": 300,
      "sif-reckitt": 400,
      stocksafetoreallocate: 34,
      suggestedallocation: 35,
    },
    {
      "Business Unit": "Health",
      Channel: "Groceries",
      Customer: "Asda",
      Location: "Germany",
      allocationconsumed: 148,
      cmuscore: 0.96,
      currentallocation: 300,
      "custsoh-current": 400,
      "custsoh-target": 900,
      "custwoc-current": 4,
      "custwoc-target": 10,
      expectedservicelevel: 0.93,
      openorders: 148,
      remainingallocation: 152,
      "sif-atf": 800,
      "sif-reckitt": 300,
      stocksafetoreallocate: 42,
      suggestedallocation: 38,
    },
    {
      "Business Unit": "Health",
      Channel: "Groceries",
      Customer: "Asda",
      Location: "Germany",
      allocationconsumed: 200,
      cmuscore: 9.19,
      currentallocation: 400,
      "custsoh-current": 300,
      "custsoh-target": 500,
      "custwoc-current": 4,
      "custwoc-target": 8,
      expectedservicelevel: 0.91,
      openorders: 200,
      remainingallocation: 200,
      "sif-atf": 200,
      "sif-reckitt": 500,
      stocksafetoreallocate: 101,
      suggestedallocation: 46,
    },
  ],
  filteredOHRdata: [],
  expandedItem: null,
  loader: false,
};

const sidebarReducer = (state = initialState, action) => {
  switch (action.type) {
    case "FETCH_SELLINFORECAST":
      return {
        ...state,
        sellinforecast: action.payload,
        selloutforecast: false,
        oosrisk: false,
        irregularpo: false,
        reallocation: false,
      };
    case "FETCH_SELLOUTFORECAST":
      return {
        ...state,
        sellinforecast: false,
        selloutforecast: action.payload,
        oosrisk: false,
        irregularpo: false,
        reallocation: false,
      };
    case "FETCH_OOSRISK":
      return {
        ...state,
        sellinforecast: false,
        selloutforecast: false,
        oosrisk: action.payload,
        irregularpo: false,
        reallocation: false,
      };
    case "FETCH_IRREGULARPO":
      return {
        ...state,
        sellinforecast: false,
        selloutforecast: false,
        oosrisk: false,
        irregularpo: action.payload,
        reallocation: false,
      };
    case "FETCH_REALLOCATION":
      return {
        ...state,
        sellinforecast: false,
        selloutforecast: false,
        oosrisk: false,
        irregularpo: false,
        reallocation: action.payload,
      };
    case "FETCH_FILTERSTATUS":
      return {
        ...state,
        filterstatus: action.payload,
      };
    case "FETCH_USERDETAILS":
      return {
        ...state,
        userDetails: action.payload,
      };
    case "FETCH_OVERVIEWHIGHRISKDATA":
      return {
        ...state,
        overviewhighriskdata: action.payload,
      };
    case "FETCH_STOCKREALLOCATIONDATA":
      return {
        ...state,
        stockreallocation: action.payload,
      };
    case "FETCH_EXPANDEDITEM":
      return {
        ...state,
        expandedItem: action.payload,
      };
    case "UPDATE_LOADER":
      return {
        ...state,
        loader: action.payload,
      };
    default:
      return state;
  }
};

export default sidebarReducer;
